language: minimal

sudo: required
services: docker

# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - bash build.sh
